- id: "1647538814035"
  alias: Kvällsljus
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: 0
  condition: []
  action:
    - type: turn_on
      device_id: 481b93ddde78677acb0b9b2aa6dabafd
      entity_id: switch.utebelysning
      domain: switch
  mode: single
- id: "1647539027785"
  alias: Släck
  description: ""
  trigger:
    - platform: time
      at: 00:00:00
    - platform: sun
      event: sunrise
      offset: 0
  condition: []
  action:
    - type: turn_off
      device_id: 481b93ddde78677acb0b9b2aa6dabafd
      entity_id: switch.utebelysning
      domain: switch
  mode: single

- id: "1647539238847"
  alias: Morgonljus
  description: ""
  trigger:
    - platform: time
      at: 06:00:00
  condition:
    - condition: sun
      before: sunrise
      after: sunset
  action:
    - type: turn_on
      device_id: 481b93ddde78677acb0b9b2aa6dabafd
      entity_id: switch.utebelysning
      domain: switch
  mode: single

- alias: Daikin autoadjust
  description: Will adjust settings based on energy price-
  trigger:
    - platform: state
      entity_id: sensor.heating_level

  condition: "{{ not is_state_attr('climate.daikin_gamla_huset', 'hvac_action', 'off') or is_state('input_boolean.offbyprice_daikin','on')  }}"
  action:
    service: >-
      {% if is_state('sensor.heating_level','Normal') %} script.set_daikin_normal
      {% elif is_state('sensor.heating_level','Eco') %} script.set_daikin_eco
      {% elif is_state('sensor.heating_level','Off') %} script.set_daikin_off
      {% else %} script.set_heating_unknown
      {% endif %}
  id: 619102838d2f47f8b2f6c37fa21aa264
  mode: single

- alias: Elpanna_on
  description: ""
  trigger:
    - platform: state
      entity_id: switch.varmegolv
      to: "on"
  condition: []
  action:
    - service: switch.turn_on
      target:
        entity_id:
          - switch.elpanna
  mode: single
  id: 2a3b1433417e4ef68c759ddb50208fee

- alias: Elpanna_off
  description: ""
  trigger:
    - platform: state
      entity_id: switch.varmegolv
      to: "off"
  condition: []
  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.elpanna
  mode: single
  id: deecc85428304ac5873019eb37b96669

- alias: Nybygget autoadjust
  description: Will adjust settings based on energy price-
  trigger:
    - platform: state
      entity_id:
        - sensor.heating_level
  condition: "{{ not is_state_attr('climate.storstugan', 'hvac_action', 'off') or is_state('input_boolean.offbyprice_nybygget','on') }}"
  action:
    service: >-
      {% if is_state('sensor.heating_level','Normal') %} script.set_nybygget_normal
      {% elif is_state('sensor.heating_level','Eco') %} script.set_nybygget_eco
      {% elif is_state('sensor.heating_level','Off') %} script.set_nybygget_off
      {% else %} script.set_heating_unknown
      {% endif %}
  id: 669b2f3946694ce1b57a48c6dd0bcd18
  mode: single

- id: "1650799729864"
  alias: Nybygget hemma
  description: "Sätter 'home' som preset mode i nybygget. "
  trigger:
    - platform: state
      entity_id: input_select.heating_level
      to: Hemma
  condition: []
  action:
    - service: climate.set_preset_mode
      data:
        preset_mode: home
      target:
        entity_id:
          - climate.hall
          - climate.kok
          - climate.sovrum_nb
          - climate.sovrum_plan2
          - climate.storstuga
          - climate.badrum
    - service: >-
        {% if is_state('sensor.heating_level','Normal') %} script.set_nybygget_normal
        {% elif is_state('sensor.heating_level','Eco') %} script.set_nybygget_eco
        {% elif is_state('sensor.heating_level','Off') %} script.set_nybygget_off
        {% else %} script.set_heating_unknown
        {% endif %}
#    - service: script.vv_nybygget_on
  mode: single

- id: "1650804270407"
  alias: Nybygget borta
  description: Sätter värme läge borta
  trigger:
    - platform: state
      entity_id: input_select.heating_level
      to: Borta
  condition: []
  action:
    - service: climate.set_preset_mode
      data:
        preset_mode: away
      target:
        entity_id:
          - climate.badrum
          - climate.hall
          - climate.kok
          - climate.sovrum_nb
          - climate.sovrum_plan2
          - climate.storstuga
    - service: >-
        {% if is_state('sensor.heating_level','Eco') %} script.set_nybygget_eco
        {% elif is_state('sensor.heating_level','Normal') %} script.set_nybygget_normal
        {% elif is_state('sensor.heating_level','Off') %} script.set_nybygget_off
        {% else %} script.set_heating_unknown
        {% endif %}
#    - service: script.vv_nybygget_off
  mode: single

- alias: Gamla huset autoadjust
  description: Will adjust settings based on energy price-
  trigger:
    - platform: state
      entity_id:
        - sensor.heating_level
  condition: "{{ not is_state_attr('climate.badrum_gamla_huset', 'hvac_action', 'off') or is_state('input_boolean.offbyprice_gamla_huset','on') }}"
  action:
    service: >-
      {% if is_state('sensor.heating_level','Normal') %} script.set_gamla_huset_normal 
      {% elif is_state('sensor.heating_level','Eco') %} script.set_gamla_huset_eco
      {% elif is_state('sensor.heating_level','Off') %} script.set_gamla_huset_off
      {% else %} script.set_heating_unknown
      {% endif %}
  mode: single

- alias: Gamla huset borta
  description: Sätter värme läge borta
  trigger:
    - platform: state
      entity_id: input_select.gamla_huset_varmelage
      to: Borta
  condition: []
  action:
    - service: climate.set_preset_mode
      data:
        preset_mode: away
      target:
        entity_id:
          - climate.badrum_gamla_huset
    - service:
        "{% if is_state('sensor.heating_level','Eco') %} script.set_gamla_huset_eco
        {% endif %}"
  mode: single

- alias: Gamla huset hemma
  description: "Sätter 'home' som preset mode i gamla huset. "
  trigger:
    - platform: state
      entity_id: input_select.gamla_huset_varmelage
      to: Hemma
  condition: []
  action:
    - service: climate.set_preset_mode
      data:
        preset_mode: home
      target:
        entity_id:
          - climate.badrum_gamla_huset
    - service:
        "{% if is_state('sensor.heating_level','Eco') %} script.set_gamla_huset_eco
        {% endif %}"
  mode: single
- alias: Pool autoadjust
  description: Will adjust settings based on energy price-
  trigger:
    - platform: state
      entity_id:
        - sensor.heating_level
  condition: "{{ not is_state_attr('climate.pool', 'hvac_action', 'off') or is_state('input_boolean.offbyprice_pool','on') }}"
  action:
    service: >-
      {% if is_state('sensor.heating_level','Normal') %} script.set_pool_normal
      {% elif is_state('sensor.heating_level','Eco') %} script.set_pool_eco
      {% elif is_state('sensor.heating_level','Off') %} script.set_pool_off
      {% else %} script.set_heating_unknown
      {% endif %}
  mode: single

- alias: Switch_on
  description: Turn switch on based on energy price
  trigger:
  - platform: state
    entity_id:
    - sensor.heating_level
    to: Normal
  action:
    service: switch.turn_on
    target:
      entity_id: switch.IKEA_of_Sweden_TRADFRI_control_outlet_37da3ffe_on_off
  mode: single

- alias: Switch_off
  description: Turn switch off based on energy price
  trigger:
    - platform: state
      entity_id:
        - sensor.heating_level
      to:
        - "Eco"
        - "Off"
  condition: []
  action:
    service: switch.turn_off
    target:
      entity_id:
        - switch.IKEA_of_Sweden_TRADFRI_control_outlet_37da3ffe_on_off
  mode: single

- alias: Circulation_top_up
  id: "195603032417"
  description: Turn circulation on to reach daily target
  trigger:
    - platform: state
      entity_id:
        - sensor.electricity_price_torngard_201
  condition: >-
    {{is_state('switch.poolcirculation','off')  and states('sensor.electricity_price_torngard_201')|float(0)
            < state_attr('sensor.electricity_price_torngard_201', 'avg_price')|float(0)
            * (1.0 + (states('input_number.niva')|float(0))/100.0 )}}
  action:
    service: script.circulation_on
  mode: single

- alias: stop_circulation_after_time
  description: Stops circulation when daily target is reached
  trigger:
    - platform: state
      entity_id: switch.poolcirculation
      from: "off"
      for: "{{states('input_text.circulation_time')}}"
      to: "on"
  action:
    - service: script.circulation_off
  mode: single

- alias: stop_circulation_by_price
  description: Stops circulation when energy price is too high
  trigger:
    - platform: state
      entity_id: sensor.electricity_price_torngard_201
  condition: ->
    {{is_state('switch.poolcirculation','on')  and states('sensor.electricity_price_torngard_201')|float(0)
            > state_attr('sensor.electricity_price_torngard_201', 'avg_price')|float(0)
            * (1.0 + (states('input_number.niva')|float(0))/100.0 )}}
  action:
    - service: script.circulation_off
  mode: single

